version: 2

jobs:
  build:
    docker:
      - image: andelf/doc-build:0.1.9
    working_directory: ~/tidbcloud/dbaas-docs

    steps:
      - checkout

      - run:
          name: install sdk and awscli
          command: |
            sudo pip3 install boto3
            sudo pip3 install awscli
            printf "%s\n" ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY} ${AWS_REGION} "json" | aws configure

      - run:
          name: "Special Check for Golang User - YOUR TAB SUCK"
          command: grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok

      - run:
          name: "Merge Makedown Files"
          command: python3 scripts/merge_by_toc.py

      - run:
          name: "Generate PDF"
          command: scripts/generate_pdf.sh

      # echo "222.222.95.49 uc.qbox.me": adds a new host
      - deploy:
          name: "Publish PDF to Qiniu and S3"
          command: |
            sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              python3 scripts/upload.py output.pdf tidbcloud-beta-en-manual.pdf;
            fi
      - run:
          name: "Copy Generated PDF"
          command: mkdir /tmp/artifacts && cp output.pdf doc.md /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
